# Generated by Django 6.0.6 on 2026-06-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='matched_skills_by_category',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='missing_skills_by_category',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='reasoning',
            field=models.TextField(blank=True, default=''),
        ),
    ]
