# Generated by Django 6.0.6 on 2026-06-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_generatedanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='content_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ingestion_status',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('INGESTED', 'Ingested'), ('FAILED', 'Failed')], default='MANUAL', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('GREENHOUSE', 'Greenhouse'), ('LEVER', 'Lever'), ('ASHBY', 'Ashby'), ('OTHER', 'Other')], default='MANUAL', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
