# Generated by Django 6.0.6 on 2026-06-04 21:54

import core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recruitingpreferences_job_relevance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('GREENHOUSE', 'Greenhouse'), ('LEVER', 'Lever'), ('ASHBY', 'Ashby')], max_length=32)),
                ('base_url', models.URLField()),
                ('company_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('scan_interval_hours', models.PositiveIntegerField(default=24)),
                ('last_scan_summary', models.JSONField(blank=True, default=core.models.default_scan_summary)),
            ],
            options={
                'ordering': ['company_name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'base_url'), name='unique_job_source_type_base_url')],
            },
        ),
    ]
